// components/products/ProductForm.vue
```vue
<template>
  <form @submit.prevent="handleSubmit" class="bg-white shadow rounded-lg p-6">
    <div class="space-y-6">
      <div class="grid grid-cols-2 gap-6">
        <div>
          <label class="block text-sm font-medium text-gray-700">Name</label>
          <input
            type="text"
            v-model="formData.name"
            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            required
          />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700">SKU</label>
          <input
            type="text"
            v-model="formData.sku"
            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            required
          />
        </div>
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700">Description</label>
        <textarea
          v-model="formData.description"
          rows="3"
          class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
        />
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700">Category</label>
        <input
          type="text"
          v-model="formData.category"
          class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
          required
        />
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700">Price</label>
        <input
          type="number"
          step="0.01"
          v-model.number="formData.price"
          class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
          required
        />
      </div>

      <div class="flex justify-end space-x-3">
        <Button variant="secondary" @click="$emit('cancel')">Cancel</Button>
        <Button type="submit">Save Product</Button>
      </div>
    </div>
  </form>
</template>

<script setup>
import { ref } from 'vue';

const props = defineProps({
  initialData: {
    type: Object,
    default: () => ({
      name: '',
      sku: '',
      description: '',
      category: '',
      price: 0
    })
  }
});

const emit = defineEmits(['submit', 'cancel']);

const formData = ref({ ...props.initialData });

const handleSubmit = () => {
  emit('submit', { ...formData.value });
};
</script>
```

// src/components/products/ProductForm.tsx
import React from 'react';
import { Button } from '../common/Button';
import { Card } from '../common/Card';
import { Product, Category } from '../../types';

interface ProductFormProps {
  categories: Category[];
  onSubmit: (product: Partial<Product>) => void;
  initialValues?: Partial<Product>;
}

export function ProductForm({ categories, onSubmit, initialValues }: ProductFormProps) {
  const [formData, setFormData] = React.useState<Partial<Product>>(
    initialValues || {
      name: '',
      sku: '',
      description: '',
      price: 0,
      stock: 0,
      alertThreshold: 0,
      category: categories[0],
      dimensions: { width: 0, height: 0, depth: 0 },
      materials: [],
    }
  );

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit(formData);
  };

  return (
    <Card className="p-6">
      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
          <div>
            <label className="block text-sm font-medium text-gray-700">Name</label>
            <input
              type="text"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            />
          </div>
          
          <div>
            <label className="block text-sm font-medium text-gray-700">SKU</label>
            <input
              type="text"
              value={formData.sku}
              onChange={(e) => setFormData({ ...formData, sku: e.target.value })}
              className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            />
          </div>

          <div className="sm:col-span-2">
            <label className="block text-sm font-medium text-gray-700">Description</label>
            <textarea
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              rows={3}
              className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700">Category</label>
            <select
              value={formData.category?.id}
              onChange={(e) => {
                const category = categories.find((c) => c.id === e.target.value);
                setFormData({ ...formData, category });
              }}
              className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            >
              {categories.map((category) => (
                <option key={category.id} value={category.id}>
                  {category.name}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700">Price</label>
            <input
              type="number"
              value={formData.price}
              onChange={(e) => setFormData({ ...formData, price: Number(e.target.value) })}
              className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            />
          </div>
        </div>

        <div className="flex justify-end space-x-3">
          <Button variant="secondary">Cancel</Button>
          <Button type="submit">Save Product</Button>
        </div>
      </form>
    </Card>
  );
}
