// src/pages/Products.jsx
import React, { useState } from 'react';
import { useStore } from '../store/useStore';
import { ProductList } from '../components/products/ProductList';
import { SearchInput } from '../components/common/SearchInput';
import { ProductVariantForm } from '../components/products/ProductVariantForm';
import { ProductDetail } from '../components/products/ProductDetail';
import { ProductActions } from '../components/products/ProductActions';
import { SupplierFilter } from '../components/products/SupplierFilter';
import {
  generateTemplateCSV,
  exportProductsToCSV,
  parseProductsCSV,
  downloadCSV
} from '../utils/productImportExport';

export default function Products() {
  const { products, addProduct, updateProduct } = useStore();
  const [search, setSearch] = useState('');
  const [selectedSupplier, setSelectedSupplier] = useState('');
  const [selectedProduct, setSelectedProduct] = useState(null);
  const [showForm, setShowForm] = useState(false);
  const [showDetail, setShowDetail] = useState(false);

  const filteredProducts = products.filter(
    (product) => {
      const matchesSearch = 
        product.name.toLowerCase().includes(search.toLowerCase()) ||
        product.variants.some(v => 
          v.sku.toLowerCase().includes(search.toLowerCase()) ||
          v.name.toLowerCase().includes(search.toLowerCase())
        );

      const matchesSupplier = !selectedSupplier || 
        product.variants.some(v => v.supplier === selectedSupplier);

      return matchesSearch && matchesSupplier;
    }
  );

  const handleEdit = (product) => {
    setSelectedProduct(product);
    setShowForm(true);
    setShowDetail(false);
  };

  const handleView = (product) => {
    setSelectedProduct(product);
    setShowDetail(true);
    setShowForm(false);
  };

  const handleImport = async (file) => {
    try {
      const importedProducts = await parseProductsCSV(file);
      importedProducts.forEach(product => {
        addProduct(product);
      });
    } catch (error) {
      console.error('Error importing products:', error);
    }
  };

  const handleExport = () => {
    const csv = exportProductsToCSV(products);
    downloadCSV(csv, 'products_export.csv');
  };

  const handleDownloadTemplate = () => {
    const template = generateTemplateCSV();
    downloadCSV(template, 'products_template.csv');
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div className="flex items-center space-x-4">
          <SearchInput
            value={search}
            onChange={setSearch}
            placeholder="Search products..."
            className="w-96"
          />
          <SupplierFilter
            products={products}
            selectedSupplier={selectedSupplier}
            onSupplierChange={setSelectedSupplier}
          />
        </div>
        <ProductActions
          onAdd={() => {
            setSelectedProduct(null);
            setShowForm(true);
            setShowDetail(false);
          }}
          onImport={handleImport}
          onExport={handleExport}
          onDownloadTemplate={handleDownloadTemplate}
        />
      </div>

      {showForm ? (
        <ProductVariantForm
          initialData={selectedProduct?.variants.find(v => v.isPrimary)}
          onSubmit={(data) => {
            if (selectedProduct) {
              updateProduct({
                ...selectedProduct,
                variants: selectedProduct.variants.map(v =>
                  v.isPrimary ? { ...v, ...data } : v
                ),
              });
            }
            setShowForm(false);
          }}
          onCancel={() => setShowForm(false)}
        />
      ) : showDetail && selectedProduct ? (
        <ProductDetail
          product={selectedProduct}
          onClose={() => {
            setShowDetail(false);
            setSelectedProduct(null);
          }}
        />
      ) : (
        <ProductList
          products={filteredProducts}
          onEdit={handleEdit}
          onView={handleView}
        />
      )}
    </div>
  );
}

// pages/inventory/products.vue
```vue
<template>
  <div class="space-y-6">
    <div class="flex justify-between items-center">
      <div class="flex items-center space-x-4">
        <SearchInput
          v-model="search"
          placeholder="Search products..."
          class="w-96"
        />
        <SupplierFilter
          :products="products"
          v-model="selectedSupplier"
        />
      </div>
      <div class="flex items-center space-x-3">
        <Button variant="secondary" :icon="FileDown" @click="handleDownloadTemplate">
          Download Template
        </Button>
        <Button variant="secondary" :icon="Upload" @click="handleImportClick">
          Import
        </Button>
        <Button variant="secondary" :icon="Download" @click="handleExport">
          Export
        </Button>
        <Button :icon="Plus" @click="handleAdd">
          Add Product
        </Button>
      </div>
    </div>

    <ProductForm
      v-if="showForm"
      :initial-data="selectedProduct?.variants.find(v => v.isPrimary)"
      @submit="handleSubmit"
      @cancel="closeForm"
    />

    <ProductDetail
      v-else-if="showDetail && selectedProduct"
      :product="selectedProduct"
      @close="closeDetail"
      @update="handleUpdate"
    />

    <ProductList
      v-else
      :products="filteredProducts"
      @edit="handleEdit"
      @view="handleView"
    />

    <input
      type="file"
      ref="fileInputRef"
      @change="handleFileChange"
      accept=".csv"
      class="hidden"
    />
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';
import { Plus, Download, Upload, FileDown } from 'lucide-vue-next';
import { useMainStore } from '~/stores/mainStore';
import { 
  generateTemplateCSV,
  exportProductsToCSV,
  parseProductsCSV,
  downloadCSV
} from '~/utils/productImportExport';

const store = useMainStore();
const fileInputRef = ref(null);

const search = ref('');
const selectedSupplier = ref('');
const selectedProduct = ref(null);
const showForm = ref(false);
const showDetail = ref(false);

const products = computed(() => store.products);

const filteredProducts = computed(() => {
  return products.value.filter((product) => {
    const matchesSearch = 
      product.name.toLowerCase().includes(search.value.toLowerCase()) ||
      product.variants.some(v => 
        v.sku.toLowerCase().includes(search.value.toLowerCase()) ||
        v.name.toLowerCase().includes(search.value.toLowerCase())
      );

    const matchesSupplier = !selectedSupplier.value || 
      product.variants.some(v => v.supplier === selectedSupplier.value);

    return matchesSearch && matchesSupplier;
  });
});

const handleAdd = () => {
  selectedProduct.value = null;
  showForm.value = true;
  showDetail.value = false;
};

const handleEdit = (product) => {
  selectedProduct.value = product;
  showForm.value = true;
  showDetail.value = false;
};

const handleView = (product) => {
  selectedProduct.value = product;
  showDetail.value = true;
  showForm.value = false;
};

const handleSubmit = (data) => {
  if (selectedProduct.value) {
    store.updateProduct({
      ...selectedProduct.value,
      variants: selectedProduct.value.variants.map(v =>
        v.isPrimary ? { ...v, ...data } : v
      ),
    });
  }
  closeForm();
};

const handleUpdate = (product) => {
  store.updateProduct(product);
};

const closeForm = () => {
  showForm.value = false;
  selectedProduct.value = null;
};

const closeDetail = () => {
  showDetail.value = false;
  selectedProduct.value = null;
};

const handleImportClick = () => {
  fileInputRef.value?.click();
};

const handleFileChange = async (event) => {
  const file = event.target.files?.[0];
  if (file) {
    try {
      const importedProducts = await parseProductsCSV(file);
      importedProducts.forEach(product => {
        store.addProduct(product);
      });
    } catch (error) {
      console.error('Error importing products:', error);
    }
    event.target.value = '';
  }
};

const handleExport = () => {
  const csv = exportProductsToCSV(products.value);
  downloadCSV(csv, 'products_export.csv');
};

const handleDownloadTemplate = () => {
  const template = generateTemplateCSV();
  downloadCSV(template, 'products_template.csv');
};
</script>
```
