// components/DashboardCard.vue
<template>
  <div class="bg-white rounded-lg shadow p-6">
    <div class="flex items-center">
      <div class="flex-1">
        <p class="text-sm font-medium text-gray-600">{{ title }}</p>
        <p
          class="mt-2 text-3xl font-semibold"
          :class="alert ? 'text-red-600' : 'text-gray-900'"
        >
          {{ value }}
        </p>
      </div>
      <div
        class="p-3 rounded-full"
        :class="alert ? 'bg-red-100' : 'bg-gray-100'"
      >
        <component
          :is="icon"
          class="h-6 w-6"
          :class="alert ? 'text-red-600' : 'text-gray-600'"
        />
      </div>
    </div>
  </div>
</template>

<script setup>
defineProps({
  title: {
    type: String,
    required: true
  },
  value: {
    type: [String, Number],
    required: true
  },
  icon: {
    type: Object,
    required: true
  },
  alert: {
    type: Boolean,
    default: false
  }
});
</script>

// src/components/dashboard/DashboardCard.tsx
import React from 'react';
import { LucideIcon } from 'lucide-react';

interface DashboardCardProps {
  title: string;
  value: string | number;
  icon: LucideIcon;
  alert?: boolean;
}

export function DashboardCard({ title, value, icon: Icon, alert = false }: DashboardCardProps) {
  return (
    <div className="bg-white rounded-lg shadow p-6">
      <div className="flex items-center">
        <div className="flex-1">
          <p className="text-sm font-medium text-gray-600">{title}</p>
          <p
            className={`mt-2 text-3xl font-semibold ${
              alert ? 'text-red-600' : 'text-gray-900'
            }`}
          >
            {value}
          </p>
        </div>
        <div
          className={`p-3 rounded-full ${
            alert ? 'bg-red-100' : 'bg-gray-100'
          }`}
        >
          <Icon
            className={`h-6 w-6 ${alert ? 'text-red-600' : 'text-gray-600'}`}
          />
        </div>
      </div>
    </div>
  );
}
