// components/price-lists/PriceListActions.vue
```vue
<template>
  <div class="flex items-center space-x-3">
    <input
      type="file"
      ref="fileInputRef"
      @change="handleFileChange"
      accept=".csv"
      class="hidden"
    />
    <Button variant="secondary" :icon="FileDown" @click="$emit('download-template')">
      Download Template
    </Button>
    <Button variant="secondary" :icon="Upload" @click="handleImportClick">
      Import
    </Button>
    <Button variant="secondary" :icon="Download" @click="$emit('export')">
      Export
    </Button>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { Download, Upload, FileDown } from 'lucide-vue-next';

const emit = defineEmits(['import', 'export', 'download-template']);
const fileInputRef = ref(null);

const handleImportClick = () => {
  fileInputRef.value?.click();
};

const handleFileChange = (event) => {
  const file = event.target.files?.[0];
  if (file) {
    emit('import', file);
    // Reset input
    event.target.value = '';
  }
};
</script>
```

// src/components/price-lists/PriceListActions.jsx
import React from 'react';
import { Download, Upload, FileDown } from 'lucide-react';
import { Button } from '../common/Button';

export function PriceListActions({ onImport, onExport, onDownloadTemplate }) {
  const fileInputRef = React.useRef(null);

  const handleImportClick = () => {
    fileInputRef.current?.click();
  };

  const handleFileChange = (event) => {
    const file = event.target.files?.[0];
    if (file) {
      onImport(file);
      // Reset input
      event.target.value = '';
    }
  };

  return (
    <div className="flex items-center space-x-3">
      <input
        type="file"
        ref={fileInputRef}
        onChange={handleFileChange}
        accept=".csv"
        className="hidden"
      />
      <Button variant="secondary" icon={FileDown} onClick={onDownloadTemplate}>
        Download Template
      </Button>
      <Button variant="secondary" icon={Upload} onClick={handleImportClick}>
        Import
      </Button>
      <Button variant="secondary" icon={Download} onClick={onExport}>
        Export
      </Button>
    </div>
  );
}
